### ISSUE TITLE
Suggestion: rename getAdvice to getAndRenderAdvice

### ISSUE THREAD

**Issue by robhuang** [sh0910/frontend-mentor-solutions#2]
I would rename the `getAdvice` function to `getAndRenderAdvice`

And then I would refactor this chunk of code into its own function called `getAdvice`:
https://github.com/sh0910/frontend-mentor-solutions/blob/eacd9875515e7b503dedf49b2da804a196aede6a/03-advice-generator-app/script.js#L10-L17

**Comment by robhuang** [comment]
Usually a `get` function only gets data and doesn't do any rendering

**Comment by sh0910** [comment]
I refactored it. Thank you :)
